language: php

addons:
  postgresql: "9.6"

notifications:
  email: none

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - DB=pgsql
  matrix:
    - MOODLE_BRANCH=MOODLE_39_STABLE
    - MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - NVMVERSION=14.0.0
  - nvm install $NVMVERSION;
  - nvm use $NVMVERSION;
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci phpunit
